### ISSUE TITLE
Broken link on website

### ISSUE THREAD

**Issue by PieSlash** [jonelo/jacksum#20]
**Describe the bug**
Broken link on website

**To Reproduce**
1. Go to 'https://jacksum.net/en/install.html'
2. Click on 'Nemo, e. g. Mint Cinnamon'
3. See error: link links to local filesystem 'file:///X:/java/products/Jacksum/web/jacksum.net/en/tutorials/integration_jacksum_linux_filebrowser.html'

**Expected behavior**
Open the correct webpage.

**Screenshots**
n/a

**Environment (please complete the following information):**
n/a

**Additional context**
n/a

**Comment by jonelo** [comment]
Good catch, thanks a lot! Fixed.
