### ISSUE TITLE
Feature request: Provide a basic terminal for Android for those who want to use jacksum on Android.

### ISSUE THREAD

**Issue by lexterror** [jonelo/jacksum#21]
Hi Jonelo,

I was wondering if you wanted to provide a basic terminal to be able to run your jar jacksum program on Android. The source code is already available and working. I was able to use command line options for jacksum on verion 2.0 of shell tools (shell terminal) and it works flawlessly. I was not able to use command line options on the latest version because it would not recognize the options. its either a bug or maybe i missed something. Also, I think it would be very useful and most of the work is already done.You could just have the terminal as an option and rename/rebrand (if allowed) your new terminal for use with jacksum.

Thank you Jonelo!

https://github.com/kakathic/Tool-Shells

**Comment by jonelo** [comment]
Hi lexterror,

thank you for the new request.

I must admit that my time is limited and for now my focus is still on Jacksum itself, and [HashGarten](https://github.com/jonelo/HashGarten) if I find some free time cycles for development. I think I shouldn't open any new construction areas/new projects for now. Thanks for your understanding. Having said this I must reject this request. However this shouldn't prevent you to create new projects or contribute to existing ones, though.

If there is a problem/bug/regression with passing command line options by using the Tool-Shells in the lastet release, I suggest to file a support request/bug report for the Tool-Shells, so other CLIs can benefit from an improvement as well.

Cheers,
jonelo

**Comment by lexterror** [comment]
Thank you Jonelo

I was able to get jacksum working on the latest version of tool-shell. it turns out that I had to run the command line options directly in the terminal and not in the "run jar" option. Thank you for your time and effort!

**Comment by lexterror** [comment]
Hi Jonelo,

I wanted to give your users another great option for running Jacksum on Android:

Free Java Terminal for Android:

Termux + OpenJDK

[https://github.com/termux/termux-app](https://4pda.to/pages/go/?u=https%3A%2F%2Fgithub.com%2Ftermux%2Ftermux-app&e=118877545)

cd /sdcard/
apt update
apt-get download openjdk-17
apt-get download libjpeg-turbo
dpkg -i *.deb

Thank you!
