### ISSUE TITLE
Install as CLI only on W10/W11.

### ISSUE THREAD

**Issue by mistergitj** [jonelo/jacksum#23]
**Describe the problem**

A clear and concise description of what the problem is.

**To Reproduce**

1. Enter the command '...'
2. See the output '...'
4. See the error

**Expected behavior**

**Screenshots**

**Environment (please complete the following information)**

Run `jacksum --info > env.txt` and attach env.txt.
Please review env.txt before attaching it to the support request, because it contains all system properties read by your JVM, and it could contain personally identifiable information (PII). Feel free to remove all lines that you don't wanna share with the public.

**Additional context**

I am new to jacksum and would like to install the latest version on my W10/W11 systems for use as a command line only. The instructions on jacksum.net appear downlevel and at least confusing. Thanks much for your help. Enjoy, John.

**Comment by jonelo** [comment]
Thank you John for your feedback.  I have just updated the manual installation instructions of Jacksum's command line interface (CLI) on Microsoft Windows 10/11 at https://jacksum.net/en/tutorials/install_jacksum_windows_commandline.html

The manual installation instructions should give users the max. flexibility to meet the requirements users have on their individual Windows environments.

Does it help you?

Kind regards,
Johann

**Comment by mistergitj** [comment]
Thank much, Johann. Enjoy, John.

    On Sunday, December 25, 2022 at 03:10:24 PM CST, Johann N. Löfflmann ***@***.***> wrote:  
 
 


Thank you John for your feedback. I have just updated the manual installation instructions of Jacksum's command line interface (CLI) on Microsoft Windows 10/11 at https://jacksum.net/en/tutorials/install_jacksum_windows_commandline.html

The manual installation instructions should give users the max. flexibility to meet the requirements users have on their individual Windows environments.

Does it help you?

Kind regards,
Johann

**Comment by mistergitj** [comment]
Johann, works fine and the DL is really jacksum-3.4.0.zip but is named jacksum-3.3.0.zip on your website, Thanks, John. 

   ----- Forwarded Message ----- From: John Christian ***@***.***>To: jonelo/jacksum ***@***.***>Sent: Sunday, December 25, 2022 at 06:37:13 PM CSTSubject: Re: [jonelo/jacksum] Install as CLI only on W10/W11. (Issue #23)
  Thank much, Johann. Enjoy, John.

    On Sunday, December 25, 2022 at 03:10:24 PM CST, Johann N. Löfflmann ***@***.***> wrote:  
 
 


Thank you John for your feedback. I have just updated the manual installation instructions of Jacksum's command line interface (CLI) on Microsoft Windows 10/11 at https://jacksum.net/en/tutorials/install_jacksum_windows_commandline.html

The manual installation instructions should give users the max. flexibility to meet the requirements users have on their individual Windows environments.

Does it help you?

Kind regards,
Johann

**Comment by jonelo** [comment]
thanks @mistergitj I have fixed that typo on the website.
