### ISSUE TITLE
Please add BLAKE2sp and BLAKE2bp support

### ISSUE THREAD

**Issue by Alepod** [jonelo/jacksum#4]
I suppose it would be quite useful. For instance, BLAKE2sp is also supported by WinRAR.

**Comment by jonelo** [comment]
Thanks for the request! Accepted, I put both on the wishlist, because they are non-broken cryptographic hash functions. 7zip supports BLAKE2sp as well (although I am not quite sure why they hide it under a "CRC" menu ;-)

**Comment by jonelo** [comment]
I didn't find any pure free Java implementations of BLAKE2sp or BLAKE2bp on the web. I believe we have to look in the reference C implementation at https://github.com/BLAKE2/BLAKE2 - the code there is licensed under the Apache 2.0 license which is compatible with Jacksum's license.

**Comment by jonelo** [comment]
I have just opened https://github.com/BLAKE2/BLAKE2/issues/75

**Comment by jonelo** [comment]
a fortnight passed, but unfortunately there is no reaction from the blake2 team. Meanwhile I have created instructions how one can add an algorithm to Jacksum. See also https://github.com/jonelo/jacksum/wiki/Supported-Algorithms#how-to-add-a-new-algorithm-to-jacksum

**Comment by jonelo** [comment]
8 months passed, and no reaction from the blake2 team. I believe we need to consider both BLAKE2sp and BLAKE2bp as legacy algorithms. Therefore putting this request as low priority as well.

**Comment by jonelo** [comment]
Just opend https://github.com/bcgit/bc-java/issues/1212 for bouncy castle.

**Comment by jonelo** [comment]
Starting with Jacksum 3.6.0, it supports BLAKE2sp, and BLAKE2bp. Kudos go to Bouncy Castle for their implementation.
