### ISSUE TITLE
Take -s into account for the default parser

### ISSUE THREAD

**Issue by jonelo** [jonelo/jacksum#9]
Jacksum 3 supports compatibility files, but it would be nice to take -s into account for the default parser (at least if -s is set to \t).
For details see also issue #6

**Comment by Alepod** [comment]
I'd also ask for that

**Comment by jonelo** [comment]
done in commit https://github.com/jonelo/jacksum/commit/ace1aabe0977d4fb740a5398bb56c07e175acf4d
